# syntax=docker/dockerfile:1
FROM golang:1.26 AS build
WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/s3ingest

FROM alpine:3.20.2
WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=build /app/main .

CMD ["./main"]
