# Build-Stage
FROM golang:1.26 AS build
WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api/main.go

# Deploy-Stage
FROM alpine:3.20.2
WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=build /app/main .

CMD ["./main"]
